### ISSUE TITLE
Suggestion | NoDebuff

### ISSUE THREAD

**Issue by JustSxm** [versai-network/Updates#2]
Just remove  speed and food from the inv and put pots instead to make the player read to go asap as they arent useful anymore

**Comment by artulloss** [comment]
Yeah, agreed because I believe the issue with hunger still dropping even when the event was canceled has been fixed.

**Comment by Tyrique01** [comment]
Add a new color for every 1000th elo

**Comment by JustSxm** [comment]
thanks for you suggestion, but you need to create a new issue, Ill do it for you

**Comment by artulloss** [comment]
what?
